trigger: none
#   main
#   feature/*

pool: todo
# parameters:
#   - dev
#   - prod

variables:
  workdir:  '$(System.DefaultWorkingDirectory)/environments/dev'

stages:
- stage:  IacValidation
  displayName: TF init-validate-Plan
  jobs:
    - job: tfinit
      displayName: Terraform till Plan
      steps:
      - task: TerraformTask@5
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(workdir)
          backendServiceArm: 'infra-todo'
          backendAzureRmResourceGroupName: 'bharatrg01'
          backendAzureRmStorageAccountName: 'bharatstg25'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform Validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'custom'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          outputTo: 'console'
          customCommand: 'fmt'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          environmentServiceNameAzureRM: 'infra-todo'

    # - job: tfapply
    #   displayName: TF Apply
    #   steps:
    #   - task: TerraformTask@5
    #     displayName: Terraform Apply
    #     continueOnError: true
    #     inputs:
    #       provider: 'azurerm'
    #       command: 'apply'
    #       workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    #       environmentServiceNameAzureRM: 'infra-todo'

    #   # - task: PowerShell@2
    #   #   displayName: Wait 2 Minutes
    #   #   inputs:
    #   #     targetType: 'inline'
    #   #     script: |
    #   #       Write-Host "Wait for 2 Minute before Destroy"
    #   #       Start-Sleep -Seconds 120

    #   # # - task: PowerShell@2
    #   # #   inputs:
    #   # #     targetType: 'inline'
    #   # #     script: |
    #   # #       echo "Resolved workdir:"
    #   # #       echo $(workdir)
    #   # #       dir $(workdir)

    # - job: tfdestroy
    #   displayName: TF destroy
    #   steps:
    #   - task: TerraformTask@5
    #     displayName: Terraform Destory
    #     condition: always()
    #     inputs:
    #       provider: 'azurerm'
    #       command: 'destroy'
    #       workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    #       environmentServiceNameAzureRM: 'infra-todo'



