trigger:
  main
  feature/*

pool: todo
parameters:
  - dev
  - prod

variables:
workdir = $(System.DefaultWorkingDirectory)

stages:
- stage:  pahla pyar
  displayName: TF init-validate-Plan
  jobs:
    - job: 
      steps:
      
    
