trigger: none
#   main
#   feature/*

pool: todo
# parameters:
#   - dev
#   - prod

variables:
workdir = $(System.DefaultWorkingDirectory)

stages:
- stage:  pahla pyar
  displayName: TF init-validate-Plan
  jobs:
    - job: 
      steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    backendServiceArm: 'infra-todo'
    backendAzureRmResourceGroupName: 'bharatrg01'
    backendAzureRmStorageAccountName: 'bharatstg25'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
      
    
